"""cria tabela verificacao

Revision ID: a82a150535a2
Revises: b7e283256795
Create Date: 2026-07-21 16:43:25.522883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82a150535a2'
down_revision: Union[str, Sequence[str], None] = 'b7e283256795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('tempo_resposta_ms', sa.Integer(), nullable=True),
    sa.Column('codigo_http', sa.Integer(), nullable=True),
    sa.Column('verificado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificacoes')
    # ### end Alembic commands ###
