"""cria coluna ultima_verificacao na tabela servico

Revision ID: b7e283256795
Revises: 034a3f0075cb
Create Date: 2026-07-21 15:48:07.780408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e283256795'
down_revision: Union[str, Sequence[str], None] = '034a3f0075cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('ultima_verificacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'ultima_verificacao')
    # ### end Alembic commands ###
