"""adiciona tipo_verificacao em servicos

Revision ID: ebd56a87f2e5
Revises: 02e64f7181df
Create Date: 2026-08-02 16:48:51.581274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd56a87f2e5'
down_revision: Union[str, Sequence[str], None] = '02e64f7181df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    tipo_enum = sa.Enum('http', 'playwright', name='tipoverificacao')
    tipo_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('tipo_verificacao', sa.Enum('http', 'playwright', name='tipoverificacao', create_type=False), server_default=sa.text("'http'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'tipo_verificacao')
    sa.Enum(name='tipoverificacao').drop(op.get_bind())
    # ### end Alembic commands ###
